#!/usr/bin/env bash
# This script ings an IP address passed as an argument as well displays 
# Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed

if [ "$1" ]
then
ping -c 5 "$1"
else
echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
