#!/usr/bin/env bash
# script that displays numbers from 1 to 100.

TALLY=1
while [ $TALLY -lt 101 ]
do
    if [ $((TALLY%15)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((TALLY%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((TALLY%5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$TALLY"
    fi
    let TALLY+=1
done

