#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes

time=0
while [ $time -lt 13 ]
do
    echo "Hour: $time"
    MINUTES=1
    while [ $time -lt 60 ]
    do
        echo $time
	let time+=1
    done
    let time+=1
done
